version: '3.7'
services:
  api:
    build:
      context: api/docker
      args: 
        git_repository: git@github.com:marcusmendes/desafio_rpg.git
        default_branch: master
    ports:
      - 8000:80
    depends_on: 
      - database
      - database_test
    command: bash -c "git pull &&
      composer install --no-interaction &&
      bin/console doctrine:migrations:migrate &&
      bin/console doctrine:fixtures:load --purge-with-truncate &&
      ./swagger.sh &&
      service php7.2-fpm start &&
      nginx -g 'daemon off;'"

  web:
    build:
      context: web/docker
      args:
        git_repository: git@github.com:marcusmendes/desafio_rpg.git
        default_branch: master
    ports:
      - 3333:80
    depends_on: 
      - api
    command: bash -c "git pull &&
      npm install &&
      npm run build &&
      nginx -g 'daemon off;'"
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio_rpg
    depends_on:
      - pgadmin
    ports:
      - 5432:5432 
  
  database_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test 
    depends_on:
      - pgadmin
    ports:
      - 5434:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80