version: '3.7'
services:
  api:
    build:
      context: api/docker
      args: 
        git_repository: git@github.com:marcusmendes/desafio_rpg.git
        default_branch: master
    ports:
      - "8000:80"
    depends_on: 
      - database
      - database_test
    command: bash -c "git pull && composer install --no-interaction --prefer-dist --no-scripts && bin/console doctrine:migrations:migrate &&  service php7.2-fpm start && nginx -g 'daemon off;'"
  
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: desafio_rpg
    ports:
      - 5432:5432 
  
  database_test:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: test 
    ports:
      - 5434:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080