index:
  path: /
  controller: App\Controller\DefaultController::index
  methods: GET

# RPG
start_round:
  path: /start
  controller: App\Controller\RPGController::startRound
  methods: GET

turn:
  path: /turn
  controller: App\Controller\RPGController::turn
  methods: POST